/** @loupe/core — shared logic for web + mobile (API client, types, hooks). */
export { configureApi, getApiConfig, type ApiConfig } from "./config";
export {
  apiFetch,
  apiFetchEnvelope,
  ApiError,
  type Envelope,
  type ErrorDetail,
} from "./client";
export { ENDPOINTS } from "./endpoints";
export { api } from "./api";
export * from "./types";
export {
  useScanLoop,
  type UseScanLoopOptions,
  type ScanLoopResult,
} from "./useScanLoop";
export {
  CARD_CHART_RANGES,
  CARD_CHART_RANGE_TO_BACKEND,
  labelForCardChartRange,
  type CardChartRange,
} from "./charts";
export {
  useApiQuery,
  useApiMutation,
  useTrending,
  useSearch,
  usePublicSearch,
  usePublicTrending,
  usePublicBrowse,
  usePublicSparklines,
  usePriceHistory,
  useMarket,
  useMarketplacePrices,
  useValuation,
  useCardSnapshot,
  useCardComps,
  useCardListings,
  useNearbyListings,
  useCardAttributes,
  useCardHoldings,
  useSetProgress,
  usePublicSets,
  usePublicSealedSearch,
  useSealedProduct,
  useSealedMarket,
  useSealedHoldings,
  useAddSealedHolding,
  useUpdateSealedHolding,
  useDeleteSealedHolding,
  useIdentifyCard,
  useCard,
  useMe,
  useEntitlements,
  useBillingConfig,
  useStartCheckout,
  useSubscribe,
  useBillingPortal,
  useRecents,
  usePutRecents,
  useLogin,
  useRegister,
  useWatchlist,
  useAddToWatchlist,
  useAnalyticsOverview,
  useHomeFeed,
  useReports,
  useUpcomingReports,
  useGenerateReport,
  useGrades,
  usePortfolioHistory,
  useAddGrade,
  useUpdateGrade,
  useDeleteGrade,
  useAlerts,
  useCreateAlert,
  useDeleteAlert,
  useResolvedCardId,
  useJobs,
  useJob,
  useApplyToJob,
  useTrackApplication,
  useBlogPosts,
  useBlogPost,
  useWaitlistStats,
  useJoinWaitlist,
  useAdminWaitlist,
  useSetWaitlistStatus,
  useDeleteWaitlistEntry,
  useAdminJobs,
  useCreateJob,
  useUpdateJob,
  useDeleteJob,
  useAdminApplications,
  useAdminApplication,
  useUpdateApplicationStatus,
  useAdminBlogPosts,
  useCreateBlogPost,
  useUpdateBlogPost,
  useDeleteBlogPost,
  useAdminMetrics,
  useAnnouncement,
  useAdminSiteConfig,
  useUpdatePlanConfig,
  useUpdateAnnouncement,
  useAdminUsers,
  useSetUserRole,
  useSetUserPlan,
  useBanUser,
  useUnbanUser,
  useDeleteUser,
  useAdminUserDetail,
  useCreateTestAccount,
  usePublicFlags,
  useFeatureFlag,
  useAdminFlags,
  useCreateFlag,
  useUpdateFlag,
  useDeleteFlag,
  useUpsertFlag,
  useAdminHealth,
  useAdminDbTables,
  useAdminDbTable,
  useAdminDbGraph,
  useAdminCloud,
  useAdminCloudLogs,
  useAdminAudit,
  useAdminAuditFacets,
  useAdminRevenue,
  useRevokeUserSessions,
  useCancelUserSubscription,
  useAdminCatalog,
  useAdminScanner,
  useAdminCards,
  useAdminCard,
  useAddCardPriceOverride,
  useAdminPulse,
  useAdminEngagement,
} from "./queries";
