/** @loupe/core — shared logic for web + mobile (API client, types, hooks). */
export { configureApi, getApiConfig, type ApiConfig } from "./config";
export {
  apiFetch,
  apiFetchEnvelope,
  ApiError,
  type Envelope,
  type ErrorDetail,
} from "./client";
export { ENDPOINTS } from "./endpoints";
export { api } from "./api";
export * from "./types";
export {
  CARD_CHART_RANGES,
  CARD_CHART_RANGE_TO_BACKEND,
  labelForCardChartRange,
  type CardChartRange,
} from "./charts";
export {
  useApiQuery,
  useApiMutation,
  useTrending,
  useSearch,
  usePublicSearch,
  usePublicTrending,
  usePublicBrowse,
  usePublicSparklines,
  usePriceHistory,
  useMarket,
  useMarketplacePrices,
  useValuation,
  useIdentifyCard,
  useCard,
  useMe,
  useLogin,
  useRegister,
  useWatchlist,
  useAddToWatchlist,
  useAnalyticsOverview,
  useHomeFeed,
  useGrades,
  useAddGrade,
  useUpdateGrade,
  useDeleteGrade,
  useResolvedCardId,
  useJobs,
  useJob,
  useApplyToJob,
  useTrackApplication,
  useBlogPosts,
  useBlogPost,
  useWaitlistStats,
  useJoinWaitlist,
  useAdminWaitlist,
  useSetWaitlistStatus,
  useDeleteWaitlistEntry,
  useAdminJobs,
  useCreateJob,
  useUpdateJob,
  useDeleteJob,
  useAdminApplications,
  useAdminApplication,
  useUpdateApplicationStatus,
  useAdminBlogPosts,
  useCreateBlogPost,
  useUpdateBlogPost,
  useDeleteBlogPost,
  useAdminMetrics,
  useAdminUsers,
  useSetUserRole,
  useBanUser,
  useUnbanUser,
  useDeleteUser,
  useAdminUserDetail,
  useCreateTestAccount,
  usePublicFlags,
  useFeatureFlag,
  useAdminFlags,
  useCreateFlag,
  useUpdateFlag,
  useDeleteFlag,
  useUpsertFlag,
} from "./queries";
