/** @loupe/core — shared logic for web + mobile (API client, types, hooks). */
export { configureApi, getApiConfig, type ApiConfig } from "./config";
export {
  apiFetch,
  apiFetchEnvelope,
  ApiError,
  type Envelope,
  type ErrorDetail,
} from "./client";
export { ENDPOINTS } from "./endpoints";
export { api } from "./api";
export {
  // Recorder + subscription (the inspector reads these).
  subscribeApiTelemetry,
  getApiLog,
  clearApiLog,
  recordApiCall,
  setApiTelemetryEnabled,
  isApiTelemetryEnabled,
  setApiTelemetryCapacity,
  // Aggregation.
  summarizeApiStats,
  summarizeApiTelemetry,
  // Pure helpers (also unit-tested).
  normalizeRoute,
  summarizeShape,
  // Source attribution.
  withApiSource,
  pushApiSource,
  popApiSource,
  peekApiSource,
  type ApiCallRecord,
  type ApiRouteStats,
  type ApiTelemetrySummary,
} from "./apiTelemetry";
export * from "./types";
export {
  useScanLoop,
  type UseScanLoopOptions,
  type ScanLoopResult,
} from "./useScanLoop";
export {
  CARD_CHART_RANGES,
  CARD_CHART_RANGE_TO_BACKEND,
  labelForCardChartRange,
  type CardChartRange,
} from "./charts";
export {
  useApiQuery,
  useApiMutation,
  useTrending,
  useSearch,
  usePublicSearch,
  usePublicTrending,
  usePublicBrowse,
  usePublicCarousels,
  usePublicCarouselsResolved,
  usePublicSparklines,
  usePriceHistory,
  useMarket,
  useMarketplacePrices,
  useValuation,
  useCardSnapshot,
  useCardComps,
  useCardListings,
  useNearbyListings,
  useCardAttributes,
  useCardHoldings,
  useCardAnalytics,
  useCardPopulation,
  useCardCerts,
  useSetProgress,
  usePublicSets,
  usePublicSealedSearch,
  useSealedProduct,
  useSealedMarket,
  useSealedHoldings,
  useAddSealedHolding,
  useUpdateSealedHolding,
  useDeleteSealedHolding,
  useIdentifyCard,
  useCard,
  useMe,
  useEntitlements,
  useBillingConfig,
  useStartCheckout,
  useSubscribe,
  useBillingPortal,
  useUserSettings,
  useUpdateUserSettings,
  useRecents,
  usePutRecents,
  useLogin,
  useRegister,
  useWatchlist,
  useAddToWatchlist,
  useAnalyticsOverview,
  useCollectionsOverview,
  useCreateCollection,
  useUpdateCollection,
  useDeleteCollection,
  useBulkAddToCollection,
  useBulkRemoveFromCollection,
  useTransferBetweenCollections,
  useHomeFeed,
  useReports,
  useUpcomingReports,
  useGenerateReport,
  useGrades,
  useVaultSummary,
  usePortfolioHistory,
  useAddGrade,
  useUpdateGrade,
  useDeleteGrade,
  useAlerts,
  useCreateAlert,
  useDeleteAlert,
  useResolvedCardId,
  useJobs,
  useJob,
  useApplyToJob,
  useTrackApplication,
  useBlogPosts,
  useBlogPost,
  useWaitlistStats,
  useJoinWaitlist,
  useAdminWaitlist,
  useSetWaitlistStatus,
  useDeleteWaitlistEntry,
  useAdminJobs,
  useCreateJob,
  useUpdateJob,
  useDeleteJob,
  useAdminApplications,
  useAdminApplication,
  useUpdateApplicationStatus,
  useAdminBlogPosts,
  useCreateBlogPost,
  useUpdateBlogPost,
  useDeleteBlogPost,
  useAdminMetrics,
  useAnnouncement,
  useAdminSiteConfig,
  useUpdatePlanConfig,
  useUpdateAnnouncement,
  useAdminUsers,
  useSetUserRole,
  useSetUserPlan,
  useBanUser,
  useUnbanUser,
  useDeleteUser,
  useAdminUserDetail,
  useCreateTestAccount,
  useCarouselRail,
  useAiSearch,
  useAiSearchLimits,
  useAiFeedback,
  useAdminAiOverview,
  useAdminAiLogs,
  useAdminAiLog,
  useAppConfig,
  AI_QUERY_MAX_CHARS,
  usePublicFlags,
  useFeatureFlag,
  useAdminFlags,
  useCreateFlag,
  useUpdateFlag,
  useDeleteFlag,
  useUpsertFlag,
  useAdminCarousels,
  useUpdateCarousel,
  useCreateCarousel,
  useDeleteCarousel,
  useResetCarousel,
  useSetCarouselAi,
  useRegenerateCarousels,
  useAdminHealth,
  useAdminEnv,
  useAdminIntegrations,
  useAdminEmailTemplates,
  useAdminEmailTemplate,
  useAdminEmailTest,
  useAdminAnnouncementPreview,
  useAdminAnnouncementSend,
  useAdminSupportSend,
  useAdminEmailLog,
  useAdminEmailLogEntry,
  useAdminEmailLogRetry,
  useAdminDbTables,
  useAdminDbTable,
  useAdminDbGraph,
  useAdminCloud,
  useAdminCloudLogs,
  useAdminAudit,
  useAdminAuditFacets,
  useAdminRevenue,
  useRevokeUserSessions,
  useCancelUserSubscription,
  useRefundUser,
  useImpersonateUser,
  useAdminCatalog,
  useAdminPriceCharting,
  useAdminPriceChartingProbe,
  useAdminPriceChartingSync,
  useAdminCardTree,
  useAdminScanner,
  useAdminScannerTrend,
  useAdminScanHistory,
  useAdminScanDetail,
  useAdminGrades,
  useAdminCards,
  useAdminCard,
  useAddCardPriceOverride,
  useAdminPulse,
  useAdminEngagement,
  useAdminRetention,
  useAdminInsightsStatus,
  useAskInsights,
} from "./queries";
