/**
 * carouselRecipes — the merchandising engine behind the marketplace.
 *
 * A **recipe** is a fully JSON-serializable carousel definition: a title plus a
 * constrained filter vocabulary (price band, rarity, sort). This is exactly how
 * large storefronts (Amazon et al.) work — they don't hand-write every shelf;
 * they keep a *pool of strategies* and a selection layer samples a varied subset
 * per visit, so the page feels fresh ("different data sets every time"). Because
 * a recipe is pure data over a fixed vocabulary, the SAME contract can be:
 *   1. authored by hand (the curated pool below),
 *   2. generated by an LLM (see `/v1/public/carousels` — AI picks creative
 *      themes + copy + the filter recipe, never the data),
 * and then compiled to a real `RailSpec` the existing `MarketplaceRail` renders.
 *
 * The compiler maps a recipe to the rail kinds we already have, so nothing new
 * is needed downstream — an AI-invented "Rainbow rares under $100" shelf renders
 * through the same path as the curated rails.
 */
import type { CarouselRecipe } from "@loupe/core";
import {
  priceOver,
  priceUnder,
  priceBetween,
  rarityMatches,
  inRarities,
  byPriceDesc,
  byPriceAsc,
  byName,
  type CardPredicate,
  type CardComparator,
} from "./cardFilters";
import type { RailSpec } from "./railCatalog";

// `CarouselRecipe` (the serializable carousel contract — what the AI generator
// emits and the curated pool is written in) lives in @loupe/core so the web and
// the API share one definition.

const COMPARATORS: Record<string, CardComparator> = {
  price_desc: byPriceDesc,
  price_asc: byPriceAsc,
  name: byName,
};

const interp = (s: string, label: string) => s.replaceAll("{label}", label);

/** Compile a serializable recipe into a real `RailSpec` for `MarketplaceRail`. */
export function recipeToRailSpec(r: CarouselRecipe, label: string): RailSpec {
  const title = interp(r.title, label);
  const subtitle = interp(r.subtitle, label);
  const minItems = r.minItems ?? 4;

  if (r.source === "catalog") {
    return {
      kind: "catalog",
      id: r.id,
      title,
      subtitle,
      sort: r.sort === "name" ? "name" : "newest",
      limit: r.limit ?? 20,
      minItems,
    };
  }

  const where: CardPredicate[] = [];
  if (r.priceMin != null && r.priceMax != null)
    where.push(priceBetween(r.priceMin, r.priceMax));
  else if (r.priceMin != null) where.push(priceOver(r.priceMin));
  else if (r.priceMax != null) where.push(priceUnder(r.priceMax));
  if (r.rarityPattern) where.push(rarityMatches(new RegExp(r.rarityPattern, "i")));
  if (r.rarities?.length) where.push(inRarities(...r.rarities));

  return {
    kind: "cards",
    id: r.id,
    title,
    subtitle,
    fetch: {
      sort: r.source === "trending" ? "trending" : "value",
      maxPrice: r.priceMax,
      limit: 24,
    },
    lens: {
      where: where.length ? where : undefined,
      sort: COMPARATORS[r.sort ?? "price_desc"],
      limit: r.limit ?? 20,
    },
    minItems,
  };
}

// ──────────────────────────────────────────────────────────────────────────
// Curated strategy pool — the always-on shelves the rotation samples from.
// (The AI generator adds more of these at runtime; see composeGameRails.)
// ──────────────────────────────────────────────────────────────────────────
export const CURATED_RECIPES: CarouselRecipe[] = [
  {
    id: "grails",
    title: "Grails & chase cards",
    subtitle: "The trophy {label} cards serious collectors hunt.",
    source: "value",
    priceMin: 250,
    sort: "price_desc",
  },
  {
    id: "rainbow",
    title: "Rainbow & secret rares",
    subtitle: "The flashiest pulls in {label}.",
    source: "value",
    rarityPattern: "secret|rainbow|illustration|special",
    sort: "price_desc",
  },
  {
    id: "premium",
    title: "Premium tier · $150+",
    subtitle: "Heavy hitters at live market value.",
    source: "value",
    priceMin: 150,
    sort: "price_desc",
  },
  {
    id: "midrange",
    title: "Collector picks · $25–$150",
    subtitle: "Standouts that won't break the bank.",
    source: "value",
    priceMin: 25,
    priceMax: 150,
    sort: "price_desc",
  },
  {
    id: "holo-hits",
    title: "Holo & ultra-rare hits",
    subtitle: "Shiny {label} cards worth chasing.",
    source: "value",
    rarityPattern: "holo|ultra|ex|gx|\\bv\\b|vmax|vstar",
    sort: "price_desc",
  },
  {
    id: "under25",
    title: "Great finds under $25",
    subtitle: "Quality {label} pickups, priced live.",
    source: "value",
    priceMax: 25,
    sort: "price_desc",
  },
  {
    id: "steals5",
    title: "Steals under $5",
    subtitle: "Affordable {label} singles.",
    source: "value",
    priceMax: 5,
    sort: "price_desc",
  },
  {
    id: "budget-binder",
    title: "Budget binder fillers",
    subtitle: "Round out the collection for less.",
    source: "value",
    priceMax: 10,
    sort: "price_asc",
  },
  {
    id: "blue-chips",
    title: "Blue-chip singles",
    subtitle: "Established, high-value {label} cards.",
    source: "value",
    priceMin: 75,
    priceMax: 400,
    sort: "price_desc",
  },
];

// ──────────────────────────────────────────────────────────────────────────
// Seeded rotation — the "fresh every visit" selection layer.
// ──────────────────────────────────────────────────────────────────────────

/** Tiny deterministic PRNG (mulberry32) so a given seed always shuffles the
 *  same way — stable within a visit, varied across visits. */
function rng(seed: number): () => number {
  let s = seed >>> 0;
  return () => {
    s |= 0;
    s = (s + 0x6d2b79f5) | 0;
    let t = Math.imul(s ^ (s >>> 15), 1 | s);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

function shuffle<T>(arr: readonly T[], seed: number): T[] {
  const out = [...arr];
  const rand = rng(seed);
  for (let i = out.length - 1; i > 0; i--) {
    const j = Math.floor(rand() * (i + 1));
    [out[i], out[j]] = [out[j]!, out[i]!];
  }
  return out;
}

/**
 * Compose the ordered rails for a game: stable "anchor" shelves plus a
 * seed-shuffled sample of the strategy pool, so the storefront varies per
 * visit like a real marketplace. `aiRecipes` (from the AI generator) are mixed
 * into the rotating pool when present.
 */
export function composeGameRails(
  label: string,
  seed: number,
  opts: { aiRecipes?: CarouselRecipe[]; rotatingCount?: number } = {},
): RailSpec[] {
  const rotatingCount = opts.rotatingCount ?? 5;

  // Anchor: a momentum shelf that always leads (priced games show real
  // trending; catalog-only games self-hide it and fall through to the rest).
  const anchorTop: RailSpec = {
    kind: "cards",
    id: "trending",
    title: `Trending in ${label}`,
    subtitle: `The ${label} cards moving most across connected marketplaces.`,
    fetch: { sort: "trending", limit: 24 },
    minItems: 4,
  };

  // Rotating middle: a varied sample of curated + AI strategies.
  const pool = [...CURATED_RECIPES, ...(opts.aiRecipes ?? [])];
  const picked = shuffle(pool, seed)
    .slice(0, rotatingCount)
    .map((r) => recipeToRailSpec(r, label));

  // Anchors that close every storefront.
  const explore: RailSpec = {
    kind: "catalog",
    id: "explore",
    title: `Explore ${label}`,
    subtitle: `A look across the ${label} catalog — open any card for details.`,
    sort: "newest",
    limit: 20,
    minItems: 4,
  };
  const sets: RailSpec = {
    kind: "sets",
    id: "sets",
    title: `Shop ${label} sets`,
    subtitle: `Browse ${label} by set — every release, with live card counts.`,
    minItems: 1,
  };
  const sealed: RailSpec = {
    kind: "sealed",
    id: "sealed",
    title: `Sealed ${label} products`,
    subtitle: "Booster boxes, ETBs, and bundles — tracked like singles.",
    minItems: 1,
  };

  return [anchorTop, ...picked, explore, sets, sealed];
}
